
[build]
target = ["x86_64-unknown-nunix-kernel.json"]

[release]
overflow-check = true
codegen-units = 1


[debug]
overflow-check = true
codegen-units = 128


[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]